# Generated by Django 6.0.2 on 2026-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agentprofile_user_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
