# Generated by Django 6.0.2 on 2026-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
