# Generated by Django 6.0.2 on 2026-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_properties_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Sqm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='living_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('for_sale', 'For Sale')], default='rent', max_length=20, null=True),
        ),
    ]
