# Generated by Django 6.0.2 on 2026-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0004_alter_properties_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('For Sale', 'For Sale')], default='rent', max_length=20, null=True),
        ),
    ]
