# Generated by Django 6.0.2 on 2026-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0005_properties_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('For Sale', 'For Sale')], default='rent', max_length=20, null=True),
        ),
    ]
