# Generated by Django 6.0.2 on 2026-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0007_alter_properties_property_type_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
