# Generated by Django 6.0.2 on 2026-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0008_alter_properties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='rent', max_length=20, null=True),
        ),
    ]
