# Generated by Django 6.0.2 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0010_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
