# Generated by Django 6.0.2 on 2026-02-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0011_properties_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='State',
            new_name='state',
        ),
    ]
